### ISSUE TITLE
Request to re-run retrieval and update

### ISSUE THREAD

**Issue by alessivs** [supermemo/SuperMemo.Discord.Archives#1]
I am done removing messages from the server which were misleading, as well as those expressed in a relaxed and non-public environment (around a dozen people, at the time?), which I did not intend to publish to the whole world. The rest of messages of my authorship were kept. Thanks for asking! Will be more observant in the future.

Can you possibly re-run the retrieval process and rewrite the tree via push or other method? Would save (me) repercussions.

EDIT: This applies to https://github.com/supermemo/SuperMemo.Discord.Archives/tree/master/SuperMemo-OG of course.

**Comment by alessivs** [comment]
Here are the details:

1. Removed messages dealing with Ordinals and the Pending queue. I no longer use or recommend ordinals to manipulate the pending queue, and the exposition is confusing and badly written. (I believe some of this made it into the Lore document as well.)
2. Removed messages containing needlessly personally-identifiable information, which was nevertheless part of friendly chatter.
3. Removed messages expressing tangentially political opinions.

You can appreciate removed messages by running a diff on the previous export, and a recent export.

Regarding (2) and (3), note that these messages were sent to a small group, which I could easily manage in my head. It's not any information I would have had a problem sharing with 2 or up to 3 dozen people *(SM "sis and bros")*, but it becomes a problem when published in the open, lacking proper context, lacking previous personal acquaintance, and coming from different social, cultural, and intellectual backgrounds. Misunderstandings and misinterpretations abound; bad intentions too. You're at risk of being cut out from services, deplatformed, bullied, ignored, etc. if you're not part of the current dominant culture. Culture changes, and so do rules, be they explicit or implicit; you're rarely in charge. I might have been too inoperative in leaving these messages linger there as the *OG* server grew.

I am asking to rewrite the tree with a new export, and this removal be reflected on *archives.supermemo.wiki*, possibly via force-push. I hope it's not too much of a hassle. Thanks.

EDIT: As brought up recently, an alternative to rewriting the history might be not version-controlling logs in public.

**Comment by alexis-** [comment]
### 1) Your request

That's no worries at all. I appreciate your thoroughness as always.

I have downloaded the chat history fresh today. For the time being I am holding onto it and taking down the archives (more on that below).

### 2) Technical implementation

Should the project continue, the pages will be hosted on this repository, and the data on a separate file server https://data.supermemo.wiki/archives/

This will remove the issue of versioning in the interest of license claims, while providing a platform for discussion and requests (through issues such as this one).

### 3) Ethical ground

We will hold a poll in the #polls channel to decide on the future of this repository.

I would like it if some debate took place beforehand. That would enable me to compile a summary of the arguments in favor and against the Archives project to put alongside the poll itself. Voting only makes sense if decisions are founded on informed opinion. And that of course is another problem in itself. Voting is a flawed institution.

I agree that TOS aren't a sufficient condition to justify publishing the chat history. The crux of the problem lies in the diffusion of public data constrained to a specific domain, into another public domain that extends far beyond the scope of the original one. Of course it can be argued that this contingency was always part of the contract since nothing barred its realization, and that lack of understanding could only be justified in the absence of freedom to access that information. However - and I dare predict that you will agree with me on this - I believe this to be abusive and dishonest since no one can truly be expected to have enough time and energy on their hands to scrupulously study and weigh the obscure complexities that every one of our decisions carry. And this is precisely what many companies prey upon.

The initial impulse behind the archives project is yet another miff with the owner of the original server. I do not want to get into details, both because it is futile and because he isn't there to defend himself. But the bottom line is that he doesn't care at all for the community and we have no idea what will happen to the server -- server that he considers his "asset".

I personally do not believe ambling through chat logs to be a very valuable use of one's time. Especially considering that most of the "golden nuggets" are already nicely laid out in [SuperMemoLore](https://github.com/supermemo/SuperMemoLore).

But I have received messages - both in public & in private - from users who seem to find value in it. And who am I to judge ?

I think it would have been beneficial if you had lingered a little longer on the server to discuss the outcome of this project.

**Comment by alexis-** [comment]
P.S. on a tangential topic, I pinged you a while ago in awesome-supermemo to get confirmation that you found satisfaction in the description of your supermemo-wine project. Have you missed it ?

https://github.com/supermemo/awesome-supermemo/issues/1

**Comment by alessivs** [comment]
Thanks for your prompt action. I was worried it would be dismissed.

The concerns expressed apply to my own content. I reviewed what is publishable and hopefully it's still useful in some form or other for future readers. If the original server had a warning or clause on relicensing or the keeping of public logs, this would be precisely the content I would have restrained from emitting (due to it being too personal, or too irrelevant). Content pertaining to the subject matter that wasn't misleading or didn't direct to obvious errors if new readers followed the advice was untouched. I would have had no problem relicensing it in the spirit of CC0 or CC-BY (whichever choice).

I do not agree on voting or polling regarding most decisions, for reasons expressed in the past, although the governance of this project might say otherwise. I chose not to belong to it, so I will not go through that process, but any of you are welcome to use this exchange as part of reasons for or against. The dilemma is reflected perhaps in the fact that I would be fine for it to exist, with the shape *my* content stands today, but I cannot answer for other people's. A seemingly useful analogy would be that of the software shop that first develops a project in-house, but then comes a new plan to go open source, so it goes through some preparation and takes precautions (IP/legal, privacy, ethical implications, etc.) before going fully open.

Regarding supermemo/awesome-supermemo#1 I'm fine (ACK-OK), and precisely the reason I suggested the repo is to *encourage* linking and the easy finding of resources in a familiar format without parsing lengthy prose. I found it unnecessary going through the discussion, for reasons of lifestyle and, again, for choosing not to be in the project.
